apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-recordings
  namespace: default
  labels:
    app: guacamole
    component: recordings

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 5Gi
