apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
  namespace: default
  labels:
    app: guacamole

spec:
  type: NodePort

  selector:
    app: guacamole

  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30085
      protocol: TCP
